#!/bin/sh
#
# Shell script to start the Unbound Docker image.
#
# Copyright 2016-2021, Frederico Martins
#   Author: Frederico Martins <http://github.com/fscm>
#
# SPDX-License-Identifier: MIT
#
# This program is free software. You can use it and/or modify it under the
# terms of the MIT License.
#

set -e

BASENAME=$(basename "${0}")
__TS__=$(date +%Y%m%d%H%M%S)


# Variables
ACTION_HELP=0
ACTION_INIT=0
ACTION_START=0

UNBOUND_SERVER_THREADS=$(nproc --ignore=1)
UNBOUND_SERVER_SLABS=$(echo "x=l(${UNBOUND_SERVER_THREADS})/l(2); scale=0; 2^(x/1)" | bc -q -l;)

__DATA_DIR__="${DATA_DIR:-/data}"
__UNBOUND_DATA__="${__DATA_DIR__}/unbound"


# Configuration files
UNBOUND_ANCHOR="${__UNBOUND_DATA__}/root.key"
UNBOUND_CONF="${__UNBOUND_DATA__}/unbound.conf"
UNBOUND_LOCAL_CONF="${__UNBOUND_DATA__}/local-zone.conf"


# Configuration file
create_config_file() {
  cat > "${UNBOUND_CONF}" <<EOF
include: "${UNBOUND_LOCAL_CONF}"
server:
  access-control: 10.0.0.0/8 allow
  access-control: 100.64.0.0/10 allow
  access-control: 127.0.0.0/8 allow
  access-control: 169.254.0.0/16 allow
  access-control: 172.16.0.0/12 allow
  access-control: 192.168.0.0/16 allow
  # access-control: fc00::/7 allow
  # access-control: fe80::/10 allow
  # access-control: ::ffff:0:0/96 allow
  aggressive-nsec: yes
  auto-trust-anchor-file: "${UNBOUND_ANCHOR}"
  cache-max-ttl: 86400
  cache-min-ttl: 300
  chroot: ""
  delay-close: 10000
  directory: "${__UNBOUND_DATA__}"
  do-daemonize: no
  do-ip6: no
  do-not-query-localhost: no
  edns-buffer-size: 1472
  harden-algo-downgrade: no
  harden-below-nxdomain: yes
  harden-dnssec-stripped: yes
  harden-glue: yes
  harden-large-queries: yes
  harden-referral-path: no
  harden-short-bufsize: yes
  hide-identity: yes
  hide-version: yes
  infra-cache-slabs: ${UNBOUND_SERVER_SLABS}
  interface: 0.0.0.0
  # interface: ::0
  key-cache-slabs: ${UNBOUND_SERVER_SLABS}
  log-local-actions: no
  log-queries: no
  log-replies: no
  log-servfail: no
  logfile: ""
  minimal-responses: yes
  msg-cache-size: 4m
  msg-cache-slabs: ${UNBOUND_SERVER_SLABS}
  neg-cache-size: 4m
  num-queries-per-thread: 4096
  num-threads: ${UNBOUND_SERVER_THREADS}
  prefetch: yes
  prefetch-key: yes
  private-address: 10.0.0.0/8
  private-address: 100.64.0.0/10
  private-address: 127.0.0.0/8
  private-address: 169.254.0.0/16
  private-address: 172.16.0.0/12
  private-address: 192.168.0.0/16
  private-address: fc00::/7
  private-address: fe80::/10
  private-address: ::ffff:0:0/96
  qname-minimisation: yes
  ratelimit: 1000
  rrset-cache-size: 4m
  rrset-cache-slabs: ${UNBOUND_SERVER_SLABS}
  rrset-roundrobin: yes
  serve-expired: yes
  so-rcvbuf: 0
  so-reuseport: yes
  so-sndbuf: 0
  #tls-cert-bundle: "/etc/ssl/certs/ca-bundle.crt"
  tls-cert-bundle: "$(openssl version -d | sed -n -e 's/.*"\(.*\)"/\1/p')/certs/ca-bundle.crt"
  unwanted-reply-threshold: 10000
  use-caps-for-id: no
  username: ""
  val-clean-additional: yes
  val-log-level: 2
  verbosity: 1
remote-control:
  control-enable: yes
  control-interface: 127.0.0.1
forward-zone:
  name: "."
  forward-addr: 1.1.1.1@53#one.one.one.one
  forward-addr: 8.8.8.8@53#dns.google
  forward-addr: 9.9.9.9@53#dns.quad9.net
  forward-addr: 1.0.0.1@53#one.one.one.one
  forward-addr: 8.8.4.4@53#dns.google
  forward-addr: 149.112.112.112@53#dns.quad9.net
  # forward-tls-upstream: yes
  # forward-addr: 1.1.1.1@853#one.one.one.one
  # forward-addr: 8.8.8.8@853#dns.google
  # forward-addr: 9.9.9.9@853#dns.quad9.net
  # forward-addr: 1.0.0.1@853#one.one.one.one
  # forward-addr: 8.8.4.4@853#dns.google
  # forward-addr: 149.112.112.112@853#dns.quad9.net
EOF
}

# Local configuration file
create_local_config_file() {
  cat > "${UNBOUND_LOCAL_CONF}" <<EOF
#local-data: "example.local. A 192.168.1.1"
#local-data-ptr: "192.168.1.1 example.local."
EOF
}

# Usage
show_usage() {
  echo "Usage: ${BASENAME} [options] (help|init|start)"
  echo "  help:"
  echo "    <none>"
  echo "  init:"
  echo "    -s <SLABS>     The Unbound DNS server number of slabs (must be a"
  echo "                   power of two bellow the 'threads' value)."
  echo "    -t <THREADS>   The Unbound DNS server number of threads."
  echo "  start:"
  echo "    <none>"
}


while getopts ":s:t:" opt; do
  case ${opt} in
    s)
      UNBOUND_SERVER_SLABS=${OPTARG}
      ;;
    t)
      UNBOUND_SERVER_THREADS=${OPTARG}
      ;;
    \?)
      echo >&2 "  [ERROR] Invalid option: -${OPTARG}"
      exit 1
      ;;
    :)
      echo >&2 "  [ERROR] Option -${OPTARG} requires an argument"
      exit 2
      ;;
  esac
done

shift $((OPTIND-1))

for command in "${@}"; do
  case "${command}" in
    [Hh][Ee][Ll][Pp])
      ACTION_HELP=1
      ;;
    [Ii][Nn][Ii][Tt])
      ACTION_INIT=1
      ;;
    [Ss][Tt][Aa][Rr][Tt])
      ACTION_START=1
      ;;
    *)
      #echo >&2 "  [WARN] Unknown command '${command}'"
      exec "$@"
      ;;
  esac
done


# Check arguments
if [ $# -eq 0 ]; then
  show_usage
  exit 3
fi
if [ "$((ACTION_HELP+ACTION_INIT+ACTION_START))" -eq 0 ]; then
  show_usage
  exit 0
fi


# Check permissions
#if [[ "$(id -u)" -ne 0 ]]; then
#  echo >&2 "  [ERROR] This script requires privileged access to system files"
#  exit 4
#fi


# === HELP ===
if [ "${ACTION_HELP}" -gt 0 ]; then
  show_usage
  exit 0
fi


# === INIT ===
if [ "${ACTION_INIT}" -gt 0 ]; then

  # Create configuration dir(s)
  if ! [ -d "${__UNBOUND_DATA__}" ]; then
    mkdir -p "${__UNBOUND_DATA__}"
    chmod 0755 "${__UNBOUND_DATA__}"
  fi

  # Backup configuration files
  if [ -f "${UNBOUND_CONF}" ]; then
    cp "${UNBOUND_CONF}" "${UNBOUND_CONF}.${__TS__}.bck"
  fi

  # Generate the configuration file
  create_config_file

  # Clean up unneeded backups
  (diff -q "${UNBOUND_CONF}" "${UNBOUND_CONF}.${__TS__}.bck" > /dev/null 2>&1 && rm -f "${UNBOUND_CONF}.${__TS__}.bck") || true

  # Generate the local configuration file
  if ! [ -f "${UNBOUND_LOCAL_CONF}" ]; then
    create_local_config_file
  fi

  # Generate the anchor file
  if ! [ -f "${UNBOUND_ANCHOR}" ]; then
    unbound-anchor -a "${UNBOUND_ANCHOR}" > /dev/null 2>&1 || echo '  [INFO] Root trust anchor file created.'
  fi

  # Generate the SSL files
  unbound-control-setup -d "${__UNBOUND_DATA__}" > /dev/null 2>&1

  # All done
  echo '  [INFO] Configuration(s) successfully updated.'
fi


# === START ===
if [ "${ACTION_START}" -gt 0 ]; then

  # Create temporary dir (if needed)
  if ! [ -d /tmp ]; then
    mkdir -m 1777 /tmp
  fi

  # Start the Unbound DNS server
  if [ -f "${UNBOUND_CONF}" ]; then
    unbound -d -p -c "${UNBOUND_CONF}"
  else
    echo >&2 '  [ERROR] Unbound DNS configuration not found.'
    exit 5
  fi
fi

# All done
exit 0
